<#
.SYNOPSIS
    Retrieves a list of pending Windows updates, either live or from the offloaded cache.
.DESCRIPTION
    Queries pending Windows updates that are not yet installed on the system.

    When Windows Update Offload is enabled ('Framework.WindowsUpdateOffload') and the '-AsTask'
    switch is NOT specified, this function reads and deserializes the update information from
    the XML cache file generated by the background scheduled task. It also evaluates the cache file
    write timestamp ('fetched' as offset in seconds, 'fetched_hr' as formatted UTC string).

    If offload is disabled or '-AsTask' is used, it queries the 'Microsoft.Update.Session'
    COM object directly.

    The updates are categorized into security updates, defender definition updates,
    update rollups, and other updates.
.FUNCTIONALITY
    Fetches and categorizes pending Windows updates for monitoring checks.
.PARAMETER AsTask
    Forces a direct live query of the Windows Update COM object, bypassing the cache file.
.PARAMETER UpdateFilter
    Optional array of wildcard strings to filter updates by title when calculating the count.
.OUTPUTS
    [hashtable] A hashtable containing update counts, reboot requirements, categorized update details,
    error messages, and fetch timestamps.
.EXAMPLE
    PS>Get-IcingaWindowsUpdatePendingList;
.EXAMPLE
    PS>Get-IcingaWindowsUpdatePendingList -UpdateFilter @('*Security*');
.EXAMPLE
    PS>Get-IcingaWindowsUpdatePendingList -AsTask;
.LINK
    https://github.com/Icinga/icinga-powershell-framework
#>

function Get-IcingaWindowsUpdatePendingList()
{
    param (
        [switch]$AsTask      = $false,
        [array]$UpdateFilter = @()
    );

    [hashtable]$PendingUpdates         = @{ };
    [hashtable]$PendingUpdateNameCache = @{ };
    $Pending                           = $null;

    # If we are not running as task, it means a check plugin is fetching the information.
    # We should test if the XML file is present deserialize the object. As the 1:1 serialize the values from
    # this function, we can entirely use the output to proceed with the update plugin output
    if (-not $AsTask -and $Global:Icinga.Protected.WindowsUpdateOffload) {
        $UpdateFile = Join-Path -Path (Get-IcingaCacheDir) -ChildPath 'provider\windows_updates\pending.xml';

        if (-not (Test-Path -Path $UpdateFile)) {
            $PendingUpdates.Add('count', 0);
            $PendingUpdates.Add('error', 'The Icinga for Windows pending update xml file is not yet present.');

            return $PendingUpdates;
        }

        $WindowsUpdates = Read-IcingaFileSecure -File $UpdateFile;
        $Pending        = ([System.Management.Automation.PSSerializer]::Deserialize($WindowsUpdates));
        $LastWriteTime  = [System.IO.File]::GetLastWriteTimeUtc($UpdateFile);
        $PendingUpdates.Add('fetched_hr', $LastWriteTime.ToString("yyyy-MM-dd HH:mm:ss 'UTC'"));
        $PendingUpdates.Add('fetched', (Get-IcingaUnixTimeOffsetNow -UnixTime ([DateTimeOffset]$LastWriteTime).ToUnixTimeSeconds()));
    } else {
        # Fetch all informations about installed updates and add them
        try {
            $WindowsUpdates = New-Object -ComObject "Microsoft.Update.Session" -ErrorAction Stop;
            $SearchIndex    = $WindowsUpdates.CreateUpdateSearcher();
            # Get a list of current pending updates which are not yet installed on the system
            $Pending        = $SearchIndex.Search("IsInstalled=0");
            $Pending        = $Pending.Updates;
        } catch {
            Exit-IcingaThrowException -ExceptionType 'Permission' -ExceptionThrown $IcingaExceptions.Permission.WindowsUpdate -Force;
        }

        $PendingUpdates.Add('fetched_hr', [DateTime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ss 'UTC'"));
        $PendingUpdates.Add('fetched', 0);
    }

    try {
        $PendingUpdates.Add('count', 0);
        $PendingUpdates.Add(
            'RebootPending',
            (Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired")
        );
        $PendingUpdates.Add(
            'updates',
            @{
                'security' = @{ };
                'defender' = @{ };
                'rollups'  = @{ };
                'other'    = @{ };
            }
        );

        foreach ($update in $Pending) {
            [hashtable]$PendingUpdateDetails = @{ };
            $PendingUpdateDetails.Add('Title', $update.Title);
            $PendingUpdateDetails.Add('Category', $null);
            $PendingUpdateDetails.Add('Deadline', $update.Deadline);
            $PendingUpdateDetails.Add('Description', $update.Description);
            $PendingUpdateDetails.Add('IsBeta', $update.IsBeta);
            $PendingUpdateDetails.Add('IsDownloaded', $update.IsDownloaded);
            $PendingUpdateDetails.Add('IsHidden', $update.IsHidden);
            $PendingUpdateDetails.Add('IsInstalled', $update.IsInstalled);
            $PendingUpdateDetails.Add('IsMandatory', $update.IsMandatory);
            $PendingUpdateDetails.Add('IsUninstallable', $update.IsUninstallable);
            $PendingUpdateDetails.Add('Languages', $update.Languages);
            $PendingUpdateDetails.Add('LastDeploymentChangeTime', $update.LastDeploymentChangeTime);
            $PendingUpdateDetails.Add('MaxDownloadSize', $update.MaxDownloadSize);
            $PendingUpdateDetails.Add('MinDownloadSize', $update.MinDownloadSize);
            $PendingUpdateDetails.Add('MoreInfoUrls', $update.MoreInfoUrls);
            $PendingUpdateDetails.Add('MsrcSeverity', $update.MsrcSeverity);
            $PendingUpdateDetails.Add('RecommendedCpuSpeed', $update.RecommendedCpuSpeed);
            $PendingUpdateDetails.Add('RecommendedHardDiskSpace', $update.RecommendedHardDiskSpace);
            $PendingUpdateDetails.Add('RecommendedMemory', $update.RecommendedMemory);
            $PendingUpdateDetails.Add('ReleaseNotes', $update.ReleaseNotes);
            $PendingUpdateDetails.Add('SecurityBulletinIDs', $update.SecurityBulletinIDs);
            $PendingUpdateDetails.Add('SupersededUpdateIDs', $update.SupersededUpdateIDs);
            $PendingUpdateDetails.Add('SupportUrl', $update.SupportUrl);
            $PendingUpdateDetails.Add('Type', $update.Type);
            $PendingUpdateDetails.Add('UninstallationNotes', $update.UninstallationNotes);
            $PendingUpdateDetails.Add('UninstallationBehavior', $update.UninstallationBehavior);
            $PendingUpdateDetails.Add('UninstallationSteps', $update.UninstallationSteps);
            $PendingUpdateDetails.Add('KBArticleIDs', $update.KBArticleIDs);
            $PendingUpdateDetails.Add('DeploymentAction', $update.DeploymentAction);
            $PendingUpdateDetails.Add('DownloadPriority', $update.DownloadPriority);
            $PendingUpdateDetails.Add('RebootRequired', $update.RebootRequired);
            $PendingUpdateDetails.Add('IsPresent', $update.IsPresent);
            $PendingUpdateDetails.Add('CveIDs', $update.CveIDs);
            $PendingUpdateDetails.Add('BrowseOnly', $update.BrowseOnly);
            $PendingUpdateDetails.Add('PerUser', $update.PerUser);
            $PendingUpdateDetails.Add('AutoSelection', $update.AutoSelection);
            $PendingUpdateDetails.Add('AutoDownload', $update.AutoDownload);

            if ($UpdateFilter.Count -ne 0) {
                foreach ($filter in $UpdateFilter) {
                    if ($update.Title -Like $filter) {
                        $PendingUpdates.count += 1;
                        break;
                    }
                }
            } else {
                $PendingUpdates.count += 1;
            }

            [string]$name = [string]::Format('{0} [{1}]', $update.Title, $update.LastDeploymentChangeTime);

            if ($PendingUpdateNameCache.ContainsKey($name) -eq $FALSE) {
                $PendingUpdateNameCache.Add($name, 1);
            } else {
                $PendingUpdateNameCache[$name] += 1;
                $name = [string]::Format('{0} ({1})', $name, $PendingUpdateNameCache[$name]);
            }

            [bool]$IsSecurity = $FALSE;
            [bool]$IsDefender = $FALSE;
            [bool]$IsRollUp   = $FALSE;

            foreach ($category in $update.Categories) {
                if ($category.Name -eq 'Update Rollups') {
                    $IsRollUp = $TRUE;
                    $PendingUpdateDetails.Category = $category;
                }
                if ($category.Name -eq 'Definition Updates' -Or $category.Name -eq 'Microsoft Defender Antivirus') {
                    $IsDefender = $TRUE;
                    $PendingUpdateDetails.Category = $category;
                    break;
                }
                if ($category.Name -eq 'Security Updates') {
                    $IsSecurity = $TRUE;
                    $PendingUpdateDetails.Category = $category;
                    break;
                }
            }

            if ($null -eq $PendingUpdateDetails.Category) {
                $PendingUpdateDetails.Category = $update.Categories[0];
            }

            if ($IsSecurity) {
                $PendingUpdates.updates.security.Add($name, $PendingUpdateDetails);
                continue;
            }
            if ($IsDefender) {
                $PendingUpdates.updates.defender.Add($name, $PendingUpdateDetails);
                continue;
            }
            if ($IsRollUp) {
                $PendingUpdates.updates.rollups.Add($name, $PendingUpdateDetails);
                continue;
            }

            $PendingUpdates.updates.other.Add($name, $PendingUpdateDetails);
        }
    } catch {
        if ($PendingUpdates.ContainsKey('Count') -eq $FALSE) {
            $PendingUpdates.Add('count', 0);
        } else {
            $PendingUpdates['count'] =  0;
        }
        $PendingUpdates.Add('error', $_.Exception.Message);
    }

    return $PendingUpdates;
}
